// swift-tools-version: 6.0
//
// Development manifest: the binary targets point at the XCFrameworks
// scripts/build.sh writes to build/Artifacts. Release tags carry a manifest
// generated by scripts/package.sh instead, whose binary targets download the
// release's zipped XCFrameworks by URL and checksum (see README.md,
// "Releases"). Do not depend on a branch of this repository; depend on a tag.

import PackageDescription

let package = Package(
    name: "heeler-overlay-natives",
    platforms: [
        .iOS(.v18),
    ],
    products: [
        .library(name: "CTailscale", targets: ["CTailscale"]),
        .library(name: "CZeroTier", targets: ["CZeroTier"]),
        .library(name: "CEasyTier", targets: ["CEasyTier"]),
    ],
    targets: [
        .binaryTarget(name: "CTailscale", path: "build/Artifacts/CTailscale.xcframework"),
        .binaryTarget(name: "CZeroTier", path: "build/Artifacts/CZeroTier.xcframework"),
        .binaryTarget(name: "CEasyTier", path: "build/Artifacts/CEasyTier.xcframework"),
    ]
)
