// swift-tools-version: 6.0
//
// Release manifest for heeler-overlay-natives v1.0.0, generated by
// scripts/package.sh: each binary target is the zipped XCFramework attached
// to the v1.0.0 release, verified by SwiftPM against its checksum. The
// development manifest on the main branch builds from build/Artifacts.

import PackageDescription

let package = Package(
    name: "heeler-overlay-natives",
    platforms: [
        .iOS(.v18),
    ],
    products: [
        .library(name: "CTailscale", targets: ["CTailscale"]),
        .library(name: "CZeroTier", targets: ["CZeroTier"]),
        .library(name: "CEasyTier", targets: ["CEasyTier"]),
    ],
    targets: [
        .binaryTarget(
            name: "CTailscale",
            url: "https://github.com/Ylarod/heeler-overlay-natives/releases/download/v1.0.0/CTailscale.xcframework.zip",
            checksum: "d5f0985ded79f2e9964aee30e86d5c2f8819c2cb9c8bee44ae96f3dbe73a8433"
        ),
        .binaryTarget(
            name: "CZeroTier",
            url: "https://github.com/Ylarod/heeler-overlay-natives/releases/download/v1.0.0/CZeroTier.xcframework.zip",
            checksum: "860d2f5a5484a1b1ab8810b0955d365bb37e931fd617a78c5d16fe88e32a8b17"
        ),
        .binaryTarget(
            name: "CEasyTier",
            url: "https://github.com/Ylarod/heeler-overlay-natives/releases/download/v1.0.0/CEasyTier.xcframework.zip",
            checksum: "7ac85b78a193943ec460fea73bc75b51b0ed3c69abd1eb20870d627aece0cf38"
        ),
    ]
)
