// swift-tools-version: 6.0
//
// Release manifest for heeler-overlay-natives v1.0.1, generated by
// scripts/package.sh: each binary target is the zipped XCFramework attached
// to the v1.0.1 release, verified by SwiftPM against its checksum. The
// development manifest on the main branch builds from build/Artifacts.

import PackageDescription

let package = Package(
    name: "heeler-overlay-natives",
    platforms: [
        .iOS(.v18),
    ],
    products: [
        .library(name: "CTailscale", targets: ["CTailscale"]),
        .library(name: "CZeroTier", targets: ["CZeroTier"]),
        .library(name: "CEasyTier", targets: ["CEasyTier"]),
    ],
    targets: [
        .binaryTarget(
            name: "CTailscale",
            url: "https://github.com/Ylarod/heeler-overlay-natives/releases/download/v1.0.1/CTailscale.xcframework.zip",
            checksum: "9cbc6469bfd6ab55ed4ffb5669e70553732e0e3b5d0137e177ce24351d906d2b"
        ),
        .binaryTarget(
            name: "CZeroTier",
            url: "https://github.com/Ylarod/heeler-overlay-natives/releases/download/v1.0.1/CZeroTier.xcframework.zip",
            checksum: "3505e60f4cfba366437eb6a0d87408c9b90a2dac0a61e01a2c3071b126034c40"
        ),
        .binaryTarget(
            name: "CEasyTier",
            url: "https://github.com/Ylarod/heeler-overlay-natives/releases/download/v1.0.1/CEasyTier.xcframework.zip",
            checksum: "220cc8f71bd3d2c686c70370bebdd3e67dd5c6a69fdb00103b0b71d11087b551"
        ),
    ]
)
