#!/bin/bash
# Packages build/Artifacts for a release tag into build/dist/<tag>:
#
#   <Framework>.xcframework.zip   one deterministic zip per XCFramework
#   Notices.zip                   Notices/ and PROVENANCE.md
#   Package.swift                 the release manifest (url + checksum)
#   checksums.txt                 `swift package compute-checksum` of each zip
#   SHA256SUMS                    every other file of the directory
#
#   scripts/package.sh <tag> [artifacts-dir]
#
# Zips are deterministic: entries sorted, every timestamp 1980-01-01, fixed
# Unix permissions, deflate level 9 (identical bytes need the same zlib,
# which python3 from the same Xcode provides). HEELER_NATIVES_REPOSITORY
# overrides the GitHub repository the manifest's URLs point at.
set -euo pipefail

# shellcheck source=lib/common.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

TAG="${1:?usage: scripts/package.sh <tag> [artifacts-dir]}"
[[ "${TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]] || die "tag must look like v1.2.3 (got ${TAG})"
ARTIFACTS="$(cd "${2:-${BUILD_DIR}/Artifacts}" && pwd -P)"
REPOSITORY="${HEELER_NATIVES_REPOSITORY:-https://github.com/Ylarod/heeler-overlay-natives}"
DIST="${BUILD_DIR}/dist/${TAG}"

"${ROOT_DIR}/scripts/verify.sh" "${ARTIFACTS}"

rm -rf "${DIST}"
mkdir -p "${DIST}"

# zip_tree <output.zip> <base-dir> <entry>...: every file and directory under
# each entry, relative to base-dir.
zip_tree() {
    python3 - "$@" <<'PY'
import os
import stat
import sys
import zipfile

output, base, *entries = sys.argv[1:]
paths = []
for entry in entries:
    top = os.path.join(base, entry)
    if os.path.isfile(top):
        paths.append(entry)
        continue
    for directory, subdirectories, files in os.walk(top):
        relative = os.path.relpath(directory, base)
        paths.append(relative + "/")
        paths.extend(os.path.join(relative, name) for name in files)
for path in paths:
    full = os.path.join(base, path)
    if os.path.islink(full.rstrip("/")):
        sys.exit(f"error: {path} is a symbolic link")

with zipfile.ZipFile(output, "w") as archive:
    for path in sorted(paths):
        info = zipfile.ZipInfo(path, date_time=(1980, 1, 1, 0, 0, 0))
        info.create_system = 3
        if path.endswith("/"):
            info.external_attr = (stat.S_IFDIR | 0o755) << 16 | 0x10
            info.compress_type = zipfile.ZIP_STORED
            archive.writestr(info, b"")
        else:
            mode = 0o755 if os.access(os.path.join(base, path), os.X_OK) else 0o644
            info.external_attr = (stat.S_IFREG | mode) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            with open(os.path.join(base, path), "rb") as handle:
                archive.writestr(info, handle.read(), compresslevel=9)
PY
}

for framework in "${FRAMEWORKS[@]}"; do
    log "zip ${framework}.xcframework"
    zip_tree "${DIST}/${framework}.xcframework.zip" "${ARTIFACTS}" "${framework}.xcframework"
done
log "zip Notices"
zip_tree "${DIST}/Notices.zip" "${ARTIFACTS}" Notices PROVENANCE.md

: > "${DIST}/checksums.txt"
for framework in "${FRAMEWORKS[@]}"; do
    zip="${DIST}/${framework}.xcframework.zip"
    checksum="$(cd "${ROOT_DIR}" && swift package compute-checksum "${zip}")"
    [[ "${checksum}" == "$(sha256_of "${zip}")" ]] || die "compute-checksum disagrees with SHA-256 for ${zip}"
    echo "${checksum}  ${framework}.xcframework.zip" >> "${DIST}/checksums.txt"
done

binary_target() {
    local framework="$1"
    cat <<EOF
        .binaryTarget(
            name: "${framework}",
            url: "${REPOSITORY}/releases/download/${TAG}/${framework}.xcframework.zip",
            checksum: "$(awk -v name="${framework}.xcframework.zip" '$2 == name { print $1 }' "${DIST}/checksums.txt")"
        ),
EOF
}

{
    cat <<EOF
// swift-tools-version: 6.0
//
// Release manifest for heeler-overlay-natives ${TAG}, generated by
// scripts/package.sh: each binary target is the zipped XCFramework attached
// to the ${TAG} release, verified by SwiftPM against its checksum. The
// development manifest on the main branch builds from build/Artifacts.

import PackageDescription

let package = Package(
    name: "heeler-overlay-natives",
    platforms: [
        .iOS(.v${DEPLOYMENT_TARGET%%.*}),
    ],
    products: [
        .library(name: "CTailscale", targets: ["CTailscale"]),
        .library(name: "CZeroTier", targets: ["CZeroTier"]),
        .library(name: "CEasyTier", targets: ["CEasyTier"]),
    ],
    targets: [
EOF
    for framework in "${FRAMEWORKS[@]}"; do
        binary_target "${framework}"
    done
    cat <<'EOF'
    ]
)
EOF
} > "${DIST}/Package.swift"

(
    cd "${DIST}"
    shasum -a 256 CTailscale.xcframework.zip CZeroTier.xcframework.zip CEasyTier.xcframework.zip \
        Notices.zip Package.swift > SHA256SUMS
)
log "Packaged ${TAG} into ${DIST#"${ROOT_DIR}/"}:"
cat "${DIST}/checksums.txt"
